#!/usr/bin/env bash

set -e

# Ansi color code variables
red="\e[0;91m"
blue="\e[0;94m"
expand_bg="\e[K"
blue_bg="\e[0;104m${expand_bg}"
red_bg="\e[0;101m${expand_bg}"
green_bg="\e[0;102m${expand_bg}"
green="\e[0;92m"
white="\e[0;97m"
bold="\e[1m"
uline="\e[4m"
reset="\e[0m"

function info {
  echo -e "\n${blue}[install]${reset} $1"
}

function error {
  echo -e "\n${red}[install]${reset} $1"
  exit 1
}

if [ "$#" -ne 1 ]; then
  error "usage: ./install SYSTEM\nsystem can be: linux, macos"
fi

system=$1

info "updating channels"
nix-channel --update

info "updating nix${reset}"
nix flake update

info "building"
nix build .\#$system

info "switch"
./result/sw/bin/darwin-rebuild switch --flake .\#$system
