[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 10.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Maple Mono NF"
style = "Bold Italic"

[font.italic]
family = "Maple Mono NF"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true
import = ["/home/folke/projects/tokyonight.nvim/extras/alacritty/tokyonight_storm.toml"]
