#!/bin/bash

ME="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

# stow . -v -d "$ME/" -t ~/ --ignore '^(dot-config|.DS_Store|sync)$' --dotfiles -n
# stow . -v -d "$ME/dot-config" -t ~/.config/ --ignore '^(.DS_Store)$' --dotfiles -n

stow . -v -d "$ME/" -t ~/ --ignore '^(.gitignore|dot-config|.DS_Store|sync|.vscode)$' --dotfiles
stow . -v -d "$ME/dot-config" -t ~/.config/ --ignore '^(.DS_Store)$' --dotfiles
