tap "amar1729/formulae"
tap "astroidmail/astroid"
tap "clementtsang/bottom"
tap "cmacrae/formulae"
tap "cowsay-org/cowsay"
tap "d12frosted/emacs-plus"
tap "eth-p/software"
tap "eugenmayer/dockersync"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "railwaycat/emacsmacport"
tap "schniz/tap"
tap "xwmx/taps"
tap "zegervdv/zathura"
# Search tool like grep, but optimized for programmers
brew "ack"
# Dungeon exploration game
brew "angband"
# Download with resuming and segmented downloading
brew "aria2"
# Spell checker with better logic than ispell
brew "aspell"
# Command-line interface for SQLite
brew "sqlite"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Terminal bandwidth utilization tool
brew "bandwhich"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# New way to see and navigate directory trees
brew "broot"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# Cross-platform make
brew "cmake"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Reimplementation of ctags(1)
brew "ctags"
# Top-like interface for container metrics
brew "ctop"
# Zstandard is a real-time compression algorithm
brew "zstd"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Secure runtime for JavaScript and TypeScript
brew "deno"
# Load/unload environment variables based on $PWD
brew "direnv"
# More intuitive version of du in rust
brew "dust"
# Maintain consistent coding style between multiple editors
brew "editorconfig"
# Modern replacement for 'ls'
brew "exa"
# XML 1.0 parser
brew "expat"
# Simple, fast and user-friendly alternative to find
brew "fd"
# User-friendly command-line shell for UNIX-like operating systems
brew "fish"
# Fast and simple Node.js version manager
brew "fnm"
# Monitor a directory for changes and run a shell command
brew "fswatch"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# GNU debugger
brew "gdb"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Syntax-highlighting pager for git and diff output
brew "git-delta"
# Blazing fast terminal-ui for git written in rust
brew "gitui"
# Generic library support script
brew "libtool"
# Manage compile and link flags for libraries
brew "pkg-config"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# GNU version of the tar archiving utility
brew "gnu-tar"
# Powerful, lightweight programming language
brew "lua"
# Command-driven, interactive function plotting
brew "gnuplot"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Version Control Visualization Tool
brew "gource"
# Library to render SVG files using Cairo
brew "librsvg"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Colorize logfiles and command output
brew "grc"
# GNU grep, egrep and fgrep
brew "grep"
# Toolkit for creating graphical user interfaces
brew "gtk+3"
# Command-line hex viewer
brew "hexyl"
# Improved top (interactive process viewer)
brew "htop"
# User-friendly cURL replacement (command-line HTTP client)
brew "httpie"
# Add GitHub support to git on the command-line
brew "hub"
# Command-line benchmarking tool
brew "hyperfine"
# GNOME XML library
brew "libxml2"
# C library for encoding, decoding, and manipulating JSON
brew "jansson"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Style and grammar checker
brew "languagetool"
# Pager program similar to more
brew "less"
# Key-value storage library with ordered mapping
brew "leveldb"
# JIT library for the GNU compiler collection
brew "libgccjit"
# Conversion library
brew "libiconv"
# Postgres C API library
brew "libpq"
# C virtualization API
brew "libvirt", restart_service: true
# Swiss Army knife of email handling
brew "mailutils"
# Utility for directing compilation
brew "make"
# Markdown parser and compiler built for speed
brew "marked"
# Show markdown documents on text terminals
brew "mdcat"
# Powerful paging program
brew "most"
# Interactive cheatsheet tool for the command-line
brew "navi"
# NCurses Disk Usage
brew "ncdu"
# Fast, highly customisable system info script
brew "neofetch"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Small build system for use with gyp or CMake
brew "ninja"
# Thread-based email index, search, and tagging
brew "notmuch"
# Libosmium-based command-line tool for processing OpenStreetMap data
brew "osmium-tool"
# Swiss-army knife of markup format conversion
brew "pandoc"
# Password manager
brew "pass"
# Pretty system information tool written in POSIX sh
brew "pfetch"
# Display the PID number for a given process name
brew "pidof"
# Pinentry for GPG on Mac
brew "pinentry-mac"
# Execute binaries from Python packages in isolated environments
brew "pipx"
# PDF rendering library (based on the xpdf-3.0 code base)
brew "poppler"
# Object-relational database system
brew "postgresql"
# Modern replacement for ps written by Rust
brew "procs"
# Emulator for x86 and PowerPC
brew "qemu"
# File browser
brew "ranger"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Utility that provides fast incremental file transfer
brew "rsync"
# Steel Bank Common Lisp system
brew "sbcl"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Autoformat shell script source code
brew "shfmt"
# Fuzzy Finder in rust!
brew "sk"
# Terminal interface for StackOverflow
brew "so"
# Cross-shell prompt for astronauts
brew "starship"
# Open source continuous file synchronization application
brew "syncthing", restart_service: true
# Very fast implementation of tldr in Rust
brew "tealdeer"
# User interface to the TELNET protocol
brew "telnet"
# Official documentation format of the GNU project
brew "texinfo"
# Text interface for Git repositories
brew "tig"
# Manage complex tmux sessions easily
brew "tmuxinator"
# Program that allows you to count code, quickly
brew "tokei"
# Internet file retriever
brew "wget"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# This is a host application for browserpass browser extension providing it access to your password store.
brew "amar1729/formulae/browserpass"
# A cross-platform graphical process/system monitor with a customizable interface and a multitude of features.
brew "clementtsang/bottom/bottom"
# Bash scripts that integrate bat with various command-line tools
brew "eth-p/software/bat-extras"
# Simple hotkey-daemon for macOS.
brew "koekeishiya/formulae/skhd"
# A tiling window manager for macOS based on binary space partitioning.
brew "koekeishiya/formulae/yabai"
cask "adoptopenjdk"
# GPU-accelerated terminal emulator
cask "alacritty"
# Application launcher and productivity software
cask "alfred"
# Utility to set a Retina display to custom resolutions
cask "avibrazil-rdm"
# Desktop password and login vault
cask "bitwarden"
# Voice and text chat software
cask "discord"
# App to build and share containerized applications and microservices
cask "docker-edge"
cask "emby-server"
# VPN client for secure internet access and private browsing
cask "expressvpn"
# Web browser
cask "firefox-developer-edition"
cask "font-comfortaa"
cask "font-dejavu-sans-mono-nerd-font"
cask "font-fantasque-sans-mono-nerd-font"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fira-sans"
cask "font-input"
cask "font-overpass"
# Fonts designed for user interfaces
cask "font-source-sans-pro"
# Desktop client for GitHub repositories
cask "github"
cask "google-backup-and-sync"
# Desktop automation application
cask "hammerspoon"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# GPU-based terminal emulator
cask "kitty"
# Host-based application firewall
cask "little-snitch"
# Full TeX Live distribution with GUI applications
cask "mactex"
cask "microsoft-teams"
cask "mullvadvpn-beta"
# Keyboard-driven, vim-like browser based on PyQt5
cask "qutebrowser"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Video game digital distribution service
cask "steam"
cask "twitch"
# Integrated development environment
cask "visual-studio-code-insiders"
# Multimedia player
cask "vlc"
# Video communication and virtual meeting platform
cask "zoom"
