# - import_tasks: repos.yml
- name: Ensure paru is installed
  become: true
  ansible.builtin.package:
    name: paru
    state: present

- name: Install packages (paru)
  become: true
  kewlfft.aur.aur:
    state: present
    use: paru
    name:
      # system
      - keyd
      - cachyos-snapper-support
      - cups
      - howdy-git
      - polkit-gnome
      - topgrade
      - xdg-desktop-portal-gnome
      - xdg-desktop-portal-hyprland
      - aria2

      # audio
      - easyeffects
      - lsp-plugins-lv2
      - zam-plugins
      - calf
      - mda.lv2
      - easyeffects-bundy01-presets
      # - jamesdsp

      # ui
      - brightnessctl
      - hyprland
      - hypridle
      - hyprland
      - hyprlock
      - hyprpaper
      - hyprpicker
      - hyprpolkitagent
      - hyprsunset
      - pavucontrol
      - rofi

      # niri
      - niri
      - mate-polkit
      - dms-shell-git

      # cli
      - atuin
      - bat
      - bob
      - btop
      - chafa
      - cliphist
      - duf
      - fd
      - fzf
      - grc
      - gum
      - htop
      - hyperfine
      - numbat-bin
      - ripgrep
      - starship
      - tealdeer
      - zoxide
      - mdcat
      - eza
      - ncdu
      - procs
      - dust
      - ranger
      - tokei
      - lazyjournal

      # dev
      - fnm-bin
      - git
      - git-crypt
      - git-delta
      - github-cli
      - httpie
      - jq
      - hub
      - just
      - lazygit
      - lazydocker
      - mermaid-cli
      - mutagen.io-bin
      - neovim
      - rustup
      - tectonic
      - wezterm
      - aspell
      - pnpm

      # apps
      - alacritty
      - kitty
      - ghostty
      - brave-bin
      - btrfs-assistant
      - rog-control-center
      - zen-browser-bin
      - discord
      - slurp
      - grim
      - grimblast-git
      - wev
      - imv
      - blueman

      # fonts
      - ttf-dejavu
      - ttf-fira-code
      - ttf-firacode-nerd
      - maplemono-ttf
      - maplemono-nf
      - ttf-ms-fonts
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-mono
      - ttf-opensans
      - ttf-victor-mono
      - ttf-victor-mono-nerd

      # Homelab
      - cv4pve-pepper-git
      - virt-viewer
