# - import_tasks: repos.yml
- name: Ensure paru is installed
  become: true
  ansible.builtin.package:
    name: paru
    state: present

- name: Install packages (paru)
  become: true
  kewlfft.aur.aur:
    state: present
    use: paru
    name:
      # system
      - aria2
      - asusctl
      - cachyos-snapper-support
      - cups
      - downgrade
      - howdy-git
      - journalctl-desktop-notification
      - keyd
      - nfs-utils
      - polkit-gnome
      - rsync
      - safeeyes
      - snapper
      - socat
      - topgrade
      - udiskie
      - wl-clip-persist
      - xdg-desktop-portal-gnome
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-hyprland
      - wavemon
      - openbsd-netcat

      # audio
      - easyeffects
      - lsp-plugins-lv2
      - zam-plugins
      - calf
      - mda.lv2
      - easyeffects-bundy01-presets
      # - jamesdsp

      # ui
      - brightnessctl
      - pavucontrol
      - rofi

      # niri
      - niri
      - mate-polkit
      - dms-shell-git

      # hyprland
      - hyprland
      - hypridle
      - hyprlock
      - hyprpaper
      - hyprpicker
      - hyprpolkitagent
      - hyprsunset

      # cli
      - atuin
      - bat
      - bob
      - btop
      - chafa
      - cliphist
      - duf
      - dust
      - eza
      - fastfetch
      - fd
      - fish
      - fzf
      - gdu
      - grc
      - gum
      - htop
      - hyperfine
      - lazyjournal
      - mdcat
      - ncdu
      - numbat-bin
      - nvtop
      - playerctl
      - plocate
      - procs
      - ranger
      - rebuild-detector
      - ripgrep
      - spotify-player
      - starship
      - tealdeer
      - tmux
      - tokei
      - trash-cli
      - yazi
      - zellij
      - zoxide

      # dev
      - act
      - ansible
      - ansible-lint
      - aspell
      - bun-bin
      - deno
      - fnm-bin
      - git
      - git-crypt
      - git-delta
      - github-cli
      - httpie
      - jq
      - just
      - lazygit
      - lazydocker
      - luacheck
      - mermaid-cli
      - mutagen.io-bin
      - neovim
      - pnpm
      - podman
      - python-pipx
      - python-uv
      - rustup
      - selene
      - stylua
      - tectonic
      - tree-sitter-cli
      - wezterm

      # apps
      - alacritty
      - blueman
      - brave-bin
      - btrfs-assistant
      - discord
      - ghostty
      - grim
      - grimblast-git
      - imv
      - kitty
      - libreoffice-fresh
      - loupe
      - nautilus
      - obsidian
      - rog-control-center
      - slurp
      - spotify-launcher
      - wev
      - zen-browser-bin

      # fonts
      - ttf-dejavu
      - ttf-fira-code
      - ttf-firacode-nerd
      - maplemono-ttf
      - maplemono-nf
      - ttf-ms-fonts
      - ttf-nerd-fonts-symbols
      - ttf-nerd-fonts-symbols-mono
      - ttf-opensans
      - ttf-victor-mono
      - ttf-victor-mono-nerd

      # Homelab
      - cv4pve-pepper-git
      - gotify-desktop
      - virt-viewer
