#!/usr/bin/bash

export SXHKD_SHELL=/usr/bin/bash
export GDK_SCALE=1
export GDK_DPI_SCALE=1
#export QT_QPA_PLATFORMTHEME=gnome
LOGS=~/.cache/bspwm/logs

exec >$LOGS/bspwm.log 2>&1

# xrdb ~/.config/bspwm/.Xresources
xsetroot -cursor_name left_ptr

deamonize() {
  echo "[start] $*"
  if pgrep "$1" >/dev/null; then
    echo "[warn] $1 is already running..."
  else
    "$@" >"$LOGS/$(basename "$1").log" 2>&1 &
  fi
}

# Launch bacground processes
deamonize nitrogen --restore
deamonize sxhkd
deamonize ~/projects/picom/build/src/picom
deamonize dunst
deamonize ~/.config/polybar/launch.sh
deamonize polydock
deamonize .config/bspwm/rules-focus.sh
deamonize greenclip daemon
deamonize xfce4-power-manager

# Start gnome keyring. Needed to unlock id_rsa and probably for Brave
eval "$(gnome-keyring-daemon --start)"
export SSH_AUTH_SOCK

echo "forked background processes"

bspc monitor -d 1 2 3 4 5 6

bspc config border_width 4
bspc config window_gap 24
#bspc config focus_follows_pointer true
bspc config focused_border_color "#5294e2"
bspc config normal_border_color "#282a36"
bspc config directional_focus_tightness low
bspc config external_rules_command ~/.config/bspwm/rules.sh

# Wal Colors!
# shellcheck source=/home/folke/.cache/wal/colors.sh
. ~/.cache/wal/colors.sh
bspc config normal_border_color "$color0"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color6"
bspc config presel_feedback_color "$color1"

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config honor_size_hints true

# Mouse Control
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
