* The Ghost Brigades
  :PROPERTIES:
  :CUSTOM_ID: the-ghost-brigades
  :END:

Author: John Scalzi Pages: 347 Score: 4.1 Series: Old Man's War Status:
Next Up

John Perry did two things on his 75th birthday. First he visited his
wife's grave. Then he joined the army.

The good news is that humanity finally made it into interstellar space.
The bad news is that planets fit to live on are scarce-- and alien races
willing to fight us for them are common. So: we fight. To defend Earth,
and to stake our own claim to planetary real estate. Far from Earth, the
war has been going on for decades: brutal, bloody, unyielding.

Earth itself is a backwater. The bulk of humanity's resources are in the
hands of the Colonial Defense Force. Everybody knows that when you reach
retirement age, you can join the CDF. They don't want young people; they
want people who carry the knowledge and skills of decades of living.
You'll be taken off Earth and never allowed to return. You'll serve two
years at the front. And if you survive, you'll be given a generous
homestead stake of your own, on one of our hard-won colony planets.

John Perry is taking that deal. He has only the vaguest idea what to
expect. Because the actual fight, light-years from home, is far, far
harder than he can imagine--and what he will become is far stranger.
