- name: Create ~/.local/share/icons/hicolor/scalable/apps
  ansible.builtin.file:
    path: ~/.local/share/icons/hicolor/scalable/apps
    state: directory
    mode: "0755"

- name: Create ~/.local/share/icons/hicolor/32x32/apps
  ansible.builtin.file:
    path: ~/.local/share/icons/hicolor/32x32/apps
    state: directory
    mode: "0755"

- name: Find icon files
  ansible.builtin.find:
    paths: "{{ dot_repo_root }}/ansible/roles/apps/files/icons/"
    recurse: false
    file_type: file
  register: dot_icons

- name: Install SVG icons
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "~/.local/share/icons/hicolor/scalable/apps/{{ item.path | basename }}"
    mode: "0644"
  loop: "{{ dot_icons.files }}"
  when: item.path.endswith('.svg')
  loop_control:
    label: "{{ item.path | basename }}"

- name: Install non-SVG icons
  ansible.builtin.copy:
    src: "{{ item.path }}"
    dest: "~/.local/share/icons/hicolor/32x32/apps/{{ item.path | basename }}"
    mode: "0644"
  loop: "{{ dot_icons.files }}"
  when: not item.path.endswith('.svg')
  loop_control:
    label: "{{ item.path | basename }}"
