#!/usr/bin/env bash

# Copyright (C) 2020-2021 Bob Hepple <bob.hepple@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

# http://bhepple.freeshell.org

# ~/.config/sway/scripts/notify sound -h int:value:$1 volume
# exit 0

PROG=$( basename $0 )
wob_pipe=~/.cache/$( basename $SWAYSOCK ).wob

case "$1" in
    -h|--help)
        echo "Usage: $PROG [percent]"
        echo
        echo "pops up wob; sets up $wob_pipe if necessary "
        exit 0
        ;;
esac

[[ "$SWAYSOCK" ]] || exit 0

# returns 0 (success) if $1 is running and is attached to this sway session; else 1
is_running_on_this_screen() {
    pkill -0 $1 || return 1
    for pid in $( pgrep $1 ); do
        WOB_SWAYSOCK="$( tr '\0' '\n' < /proc/$pid/environ | awk -F'=' '/^SWAYSOCK/ {print $2}' )"
        if [[ "$WOB_SWAYSOCK" == "$SWAYSOCK" ]]; then
            return 0
        fi
    done
    return 1
}

new_value=$1 # null or a percent; no checking!!

[[ $new_value -gt 100 ]] && new_value=100

[[ -p $wob_pipe ]] || mkfifo $wob_pipe

# wob does not appear in $(swaymsg -t get_msg), so:
is_running_on_this_screen wob || {
    tail -f $wob_pipe | wob &
}

# sometimes this hangs - need to use a timeout and restart wob if necessary:
[[ "$new_value" ]] && echo $new_value > $wob_pipe
