- name: Copy Niri Greetd config
  become: true
  ansible.builtin.copy:
    src: roles/system/files/greetd/dms-niri.kdl
    dest: /etc/greetd/dms-niri.kdl
    owner: root
    group: root
    mode: "0644"

- name: Copy Greetd config
  become: true
  ansible.builtin.copy:
    src: roles/system/files/greetd/config.toml
    dest: /etc/greetd/config.toml
    owner: root
    group: root
    mode: "0644"

- name: Enable greetd service
  become: true
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: greetd
