- name: Set list of PAM files for Howdy
  ansible.builtin.set_fact:
    pam_files:
      - sudo
      - login
      - gdm-password
      # - system-local-login
      - hyprlock
      - su

- name: Insert pam_unix line for fallback to password
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/pam.d/{{ item }}"
    line: "auth sufficient /lib/security/pam_howdy.so"
    insertafter: "^#%PAM-1.0"
    state: present
  loop: "{{ pam_files }}"
