#!/bin/env bash

notify=~/.scripts/notify

if pkill -INT wf-recorder; then
	$notify screenshot "Video Captured"
else
	nohup wf-recorder -c libx264rgb -g "$(slurp)" -f "$HOME/screenshots/mov-$(date +"%Y-%m-%d--%H-%M-%S.mp4")" &
	disown
	$notify screenshot "Video Capture Started"
fi
