#!/bin/bash

cmd=$1
ret=$(bash -c "$cmd" 2>&1)
exitCode=$?
ret=$(echo "$ret" | head -n 10)

echo "$ret"
if [ $exitCode -eq 0 ]; then
  if [ -z "$2" ]; then
    dunstify "\$ $cmd" "$ret"
  else
    dunstify "$2"
  fi
else
  if [ -z "$3" ]; then
    dunstify -u critical "\$ $cmd" "$ret"
  else
    dunstify -u critical "$3" "$ret"
  fi
fi
