#!/bin/bash

function get_icon {
  fd -1 -p "scalable.*$1" ~/.local/share/icons/Fluent \
    || fd -1 -p "$1" ~/.local/share/icons/Fluent \
    || echo "$1"
}

icon=$(get_icon "$1")
shift

notify-send -i "$icon" "$@"
