#!/bin/env fish

function export-json -a prefix
    read -z json
    for line in (printf "%s" $json | jq -r 'to_entries[] | "\(.key)=\(.value)"')
        set parts (string split -m1 '=' -- $line)
        if test "$parts[2]" != null
            set -gx {$prefix}{$parts[1]} $parts[2]
        end
    end
end

niri msg --json workspaces | jq -r '.[] | select(.is_focused==true)' | export-json ws_
niri msg --json windows | jq -r '.[] | select(.app_id=="folke.scratchpad")' | export-json sp_

if test -z "$sp_id"
    echo start
    niri msg action focus-workspace 99
    niri msg action spawn -- ghostty --class="folke.scratchpad"
    exit 0
else if test "$sp_workspace_id" = "$ws_id"
    echo hide
    niri msg action focus-workspace "$ws_idx"
else
    echo show
    niri msg action focus-window --id "$sp_id"
end
