#!/bin/env bash

WORKSPACE=$(hyprctl clients -j | jq -rec '.[] | select(.class == "folke.quake") | .workspace .name')
# TERM_CMD="kitty -1 --class=\"folke.quake\" -o background_opacity=0.90 -o hide_window_decorations=yes -o remember_window_size=no"
# TERM_CMD="wezterm --config window_background_opacity=0.9 start --class folke.quake"
TERM_CMD="ghostty --class=\"folke.quake\""

# hyprctl --batch '
# keyword windowrulev2 float,class:quake ;
# keyword windowrulev2 center,class:quake ;
# keyword windowrulev2 dimaround,class:quake ;
# keyword windowrulev2 size 1600 1000,class:quake ;
# keyword windowrulev2 pin,class:quake ;
# '
echo "WORKSPACE: $WORKSPACE"

if [ -z "$WORKSPACE" ]; then
  echo "start"
  # hyprctl dispatch -- exec "[float;size 1600 1000;center] $TERM_CMD"
  hyprctl dispatch -- exec "$TERM_CMD"
elif [ "$WORKSPACE" == "special:quake" ]; then
  echo "show"

  # Store the current active window address
  hyprctl activewindow | head -n1 | cut -f2 -d ' ' >/tmp/hypr-quake-address

  # If the current active window is fullscreen, unfullscreen it
  hyprctl activewindow | rg "fullscreen: 1" && hyprctl dispatch fullscreenstate 0 0

  # Move the quake window to the current workspace, focus it, and bring it to the top
  hyprctl dispatch movetoworkspacesilent "+0,class:^(folke\.quake)\$"
  hyprctl dispatch focuswindow "class:^(folke\.quake)\$"
  hyprctl dispatch bringactivetotop
else
  echo "hide"

  # Move the quake window to the special workspace
  hyprctl dispatch movetoworkspacesilent "special:quake,class:^(folke\.quake)\$"

  # Focus the previously active window and bring it to the top
  hyprctl dispatch focuswindow "address:0x$(cat /tmp/hypr-quake-address)"
  hyprctl dispatch bringactivetotop
fi
